development:
  apxu_api_key: Rails.application.secrets.apxu_api_key
production:
  apxu_api_key: Rails.application.secrets.apxu_api_key
production:
  apxu_api_key: Rails.application.secrets.apxu_api_key
