User.destroy_all

u1 = User.create username: "Anna", email: "anna@ga.com", password: "chicken", password_confirmation: "chicken", bio: "Most generous girl", address: 'Vietnam', admin: 1, image: '../img/pooh_bear_by_kunal908-d67le2z.png'
u2 = User.create username: "Bagi", email: "bagi@ga.com", password: "chicken", password_confirmation: "chicken", bio: "Happy always", address: 'India', admin: 0, image: '../img/355011-piglet_disney_1.jpg'
u3 = User.create username: "Linna", email: "linna@ga.com", password: "chicken", password_confirmation: "chicken", bio: "hard worker", address: 'New Zealand', admin: 0, image: '../img/277e4e7c6c1c0d2d927d68289e6eb8d7.jpg'

puts "Created #{ User.all.length } users"

City.destroy_all
c1 = City.create name: 'Paris', image: '../img/v2exl2nje6lsczqgxklf2mh1qjkhmfu-xlarge.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.'


c2 = City.create name: 'London', image: '../img/1491582155388.jpeg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.'

c3 = City.create name: 'New York', image: '../img/new-york-city-cityscape-skyline-with-statue-of-liberty-shutterstock_339298199.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.'

c4 = City.create name: 'Hanoi', image: '../img/Hoan-Kiem-lake1.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.'

c5 = City.create name: 'Sydney', image: 'sydney.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.'

c6 = City.create name: 'Melbourne', image: '../img/things-to-do-in-melbourne.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.'

c7 = City.create name: 'Phuket', image: '../img/wbislands0715-phuket.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.'

c8 = City.create name: 'Lisbon', image: '../img/Lisbon-weekend-1500x800.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.'

c9 = City.create name: 'Los Angeles', image: '../img/accuweather-los-angeles.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.'

c10 = City.create name: 'Dubai', image: '../img/Dubai_3050265k.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.'


c11 = City.create name: 'Copenhagen', image: '../img/70ea56ffb7412ee5ca4c9d1b2dbd85b9f8eca22a_1100.jpeg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.'


c12 = City.create name: 'Berlin', image: '../img/Think-Germany-Berlin-452534461-SeanPavonePhoto-copy.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.'



puts "Created #{City.all.length} cities."




Post.destroy_all

p1 = Post.create title: 'Trip to Sydney.', image: '../img/09558a73_z.jpg', city: c5 , user: u2, address: '1 Market St, Sydney', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

p2 = Post.create title: 'BEST city in the world.', image: '../img/maxresdefault.jpg', city: c3, user: u1, address: 'New York City, United States', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


p3 = Post.create title: 'Phuket is beautiful.', image: '../img/68751_232_z.jpg', city: c7, user: u1, address: 'Patong beach, Phuket, Thailand', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


p4 = Post.create title: 'Phuket trip.', image: '../img/maxresdefault.jpg', city: c7, user: u3, address: 'Bangla Road, Patong, Phuket, Thailand', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

p5 = Post.create title: 'Sydney is wonderful!', image: '../img/e706ad98_z.jpg', city: c5, user: u2, address: 'George street, Sydney, Australia', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


p6 = Post.create title: 'Dubai adventure.', image: '../img/maxresdefault.jpg', city: c10, user: u2, address: 'Jumeirah Beach Road,Jumeria 1 - Dubai - United Arab Emirates', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

p7 = Post.create title: 'Melbourne CBD.', image: '../img/1200px-Flinders_street_train_station_melbourne.jpg', city: c6, user: u3, address: 'Flinder street, Melbourne, Australia', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


p8 = Post.create title: 'Work trip to London.', image: '../img/CoventGardenAppleMarket_VisitLondon_Pawel_Libera.jpg', city: c2, user: u1, address: 'London, England', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


p9 = Post.create title: 'My hometown, Hanoi.', image: '../img/hanoi-old-quarter15-1200x800.jpg', city: c4, user: u1, address: 'Old quarter, Hanoi, Vietnam', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


p10 = Post.create title: 'Los Angeles.', image: '../img/Rodeo_Drive%2C_Beverly_Hills%2C_LA%2C_CA%2C_jjron_21.03.2012.jpg', city: c9, user: u3, address: 'Beverly Hills, Los Angeles, California, United States', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


p11 = Post.create title: 'Vibrant Lisbon.', image: '../img/image.jpg', city: c8, user: u1, address: 'Lisbon, Portugal', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


p12 = Post.create title: 'Paris,
Je Taime.', image: '../img/paris-lead.jpg', city: c1, user: u2, address: 'Paris, France', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


p13 = Post.create title: 'Hanoi in my heart.', image: '../img/west-lake-hanoi-6.jpg', city: c4, user: u1, address: 'Hanoi, Vietnam', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


p14 = Post.create title: 'New York city.', image: '../img/tripadvisortimessquare_taggeryanceyiv_5912__x_large.jpg', city: c3 , user: u3, address: 'Times Square, New York City, United States', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


p15 = Post.create title: 'City of Spires', image: '../img/ecm-253014-silversea-european-cruises-svolvaer-norway.jpg', city: c11 , user: u1, address: 'nyhavn denmark', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

p16 = Post.create title: 'Trip to Copenhagen', image: '../img/gen_copenhagen-19_rgb_1600px.jpg', city: c11 , user: u2, address: 'Copenhagen, Denmark', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


p17 = Post.create title: 'Discover Berlin.', image: '../img/berlin-city-eu-flag-over-reichstag-travel-to-germany-above-view-berlin-city-eu-flag-over-reichstag-september-103841376.jpg', city: c12 , user: u1, address: 'Berlin, Germany', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

p18 = Post.create title: 'My trip to Germany.', image: '../img/1-6410212793.png', city: c12, user: u3, address: 'Berlin, Germany', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

puts "Created #{Post.all.length} posts."

Photo.destroy_all

o1 = Photo.create image: '../img/image.jpg', city: c5
o2 = Photo.create image: '../img/My-Detour-Private-Sydney-Tour-1.png', city: c5
o3 = Photo.create image: '../img/TarongeCentenaryHeader-678x381.jpg', city: c5
o4 = Photo.create image: '../img/csm_save_and_stay_beach_18_5a12a640be.jpg', city: c7
o5 = Photo.create image: '../img/thailand-phuket-market-bangla.jpg', city: c7
o6 = Photo.create image: '../img/lisboncity1.jpg', city: c8
o7 = Photo.create image: '../img/RmTDena4Seq3l5ukZMe6_16936189_10210992136333259_215753632_o.jpg', city: c3
o8 = Photo.create image: '../img/los-angeles-and-hollywood.jpg', city: c9
o9 = Photo.create image: '../img/pov-driving-sunshine-climate-tropical-palm-trees-los-angeles-beverly-hills_vj317lmje__F0000.png', city: c9
o10 = Photo.create image: '../img/turtle-lake-temple.jpg', city: c4
o11 = Photo.create image: '../img/TPHanoi08.JPG', city: c4
o12 = Photo.create image: '../img/8804_ho_00_p_2048x1536.jpg', city: c6
o13 = Photo.create image: '../img/v1_melbourne_getting_around_hero@2x.jpg', city: c6
o14 = Photo.create image: '../img/lisbon-guide-_-what-to-do-in-lisbon-_-sightseeing-lissabon22.jpg', city: c8
o15 = Photo.create image: '../img/dubai2.jpg', city: c10
o16 = Photo.create image: '../img/Vietnam-Hanoi-Streets-Flowers.jpg', city: c4
o17 = Photo.create image: '../img/Lisbon_Street%2C_Portugal_%288619812026%29.jpg', city: c8
o18 = Photo.create image: '../img/1200px-Flinders_Street_Station_during_White_Night.jpg', city: c6
o19 = Photo.create image: '../img/events-and-whats-on-in-your-city.jpg', city: c6
o20 = Photo.create image: '../img/7315af626e990eb88bf64b0199bc7020.jpg', city: c1
o21 = Photo.create image: '../img/depositphotos_20300561-stock-photo-louvre-museum-and-pont-du.jpg', city: c1
o22 = Photo.create image: '../img/new-york-city-cityscape-skyline-with-statue-of-liberty-shutterstock_339298199.jpg', city: c3
o23 = Photo.create image: '../img/Atlantis-The-Palm.jpg', city: c10
o24 = Photo.create image: '../img/London_Eye_Twilight_April_2006.jpg', city: c2
o25 = Photo.create image: '../img/iStock-510212642.jpg', city: c2
o26 = Photo.create image: '../img/ecm-253014-silversea-european-cruises-svolvaer-norway.jpg', city: c11
o27 = Photo.create image: '../img/gen_copenhagen-19_rgb_1600px.jpg', city: c11
o28 = Photo.create image: '../img/berlin-city-eu-flag-over-reichstag-travel-to-germany-above-view-berlin-city-eu-flag-over-reichstag-september-103841376.jpg', city: c12
o29 = Photo.create image: '../img/1-6410212793.png', city: c12
o30 = Photo.create image: '../img/parisian-cafe-angela-wakefield-1500.jpg', city: c1

puts "Created #{Photo.all.length} photos."


Comment.destroy_all

cm1 = Comment.create content: 'Sydney is the best place ever.', post: p1, user: u1
cm2 = Comment.create content: 'Sydney is really cool.', post: p1, user: u2
cm3 = Comment.create content: 'I love Phuket.', post: p3, user: u1
cm4 = Comment.create content: 'I have not visited Phuket.', post: p3, user: u3
cm5 = Comment.create content: 'New York is amazinggg!!!', post: p2, user: u2
cm6 = Comment.create content: 'Phuket is lovely.', post: p4, user: u3
cm7 = Comment.create content: 'Sydney is the greatest city to live in.', post: p5, user: u1
cm8 = Comment.create content: 'My trip to Dubai was really great!', post: p6, user: u2
cm9 = Comment.create content: 'People from Melbourne are really friendly!', post: p7, user: u3
cm10 = Comment.create content: 'London markets are brilliant!!!', post: p8, user: u2
cm11 = Comment.create content: 'Hanoi street food is one of the best in the world!', post: p9, user: u1
cm12 = Comment.create content: 'I once met Channing Tatum in LA.', post: p10, user: u1
cm13 = Comment.create content: 'I have not been to Lisbon, but I would love to go there in the near future.', post: p11, user: u3
cm14 = Comment.create content: 'Paris was not as great as I expected...', post: p12, user: u1
cm15 = Comment.create content: 'People of Hanoi are lovely.', post: p13, user: u2
cm16 = Comment.create content: 'New York nightlife is so good.', post: p14, user: u1
cm17 = Comment.create content: 'I love the variety of food in Melbourne.', post: p7, user: u3
cm18 = Comment.create content: 'I have not visited Dubai.', post: p6, user: u1

puts "Created #{Comment.all.length} comments."
