

User.destroy_all

u1 = User.create username: "Anna", email: "anna@ga.com", password: "chicken", password_confirmation: "chicken", bio: "Most generous girl"
u2 = User.create username: "Bagi", email: "bagi@ga.com", password: "chicken", password_confirmation: "chicken", bio: "Happy always"
u3 = User.create username: "Linna", email: "linna@ga.com", password: "chicken", password_confirmation: "chicken", bio: "hard worker"

puts "Created #{ User.all.length } Users"

City.destroy_all
c1 = City.create name: 'Paris', image: 'https://www.telegraph.co.uk/content/dam/video_previews/v/2/v2exl2nje6lsczqgxklf2mh1qjkhmfu-xlarge.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


c2 = City.create name: 'London', image: 'https://travel.home.sndimg.com/content/dam/images/travel/fullset/2015/05/28/big-ben-london-england.jpg.rend.hgtvcom.1280.960.suffix/1491582155388.jpeg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

c3 = City.create name: 'New York', image: 'https://www.holidayguru.ie/wp-content/uploads/2018/01/new-york-city-cityscape-skyline-with-statue-of-liberty-shutterstock_339298199.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

c4 = City.create name: 'Hanoi', image: 'https://hanoitourist.info/wp-content/uploads/2016/08/Hoan-Kiem-lake1.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

c5 = City.create name: 'Sydney', image: 'https://dynaimage.cdn.cnn.com/cnn/q_auto,w_1024,c_fill,g_auto,h_576,ar_16:9/http%3A%2F%2Fcdn.cnn.com%2Fcnnnext%2Fdam%2Fassets%2F170220102107-sydney-habour.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

c6 = City.create name: 'Melbourne', image: 'https://res.cloudinary.com/redballoon/c_fill,f_auto/v1523942375/NEW%20Subcat%20Hero%20Images/things-to-do-in-melbourne.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

c7 = City.create name: 'Phuket', image: 'http://cdn-image.travelandleisure.com/sites/default/files/wbislands0715-phuket.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

c8 = City.create name: 'Lisbon', image: 'https://www.thetimes.co.uk/travel/s3/growthtravel-prod/uploads/2016/05/Lisbon-weekend-1500x800.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

c9 = City.create name: 'Los Angeles', image: 'https://accuweather.brightspotcdn.com/dims4/default/4610650/2147483647/resize/590x/quality/90/?url=http%3A%2F%2Faccuweather-bsp.s3.amazonaws.com%2F8a%2Fb1%2Ff2c7c73d422fa7c5163f98b453a0%2Flos-angeles.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

c10 = City.create name: 'Dubai', image: 'https://www.pakistankakhudahafiz.com/pkkhnew/wp-content/uploads/2016/02/Dubai_3050265k.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'



puts "Created #{City.all.length} cities."




Post.destroy_all

p1 = Post.create title: 'Trip to Sydney', image: 'https://exp.cdn-hotels.com/hotels/18000000/17340000/17337700/17337699/09558a73_z.jpg', city_id: 5 , user_id: 2, content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

p2 = Post.create title: 'BEST city in the world', image: 'https://i.ytimg.com/vi/dzjQ-akB3BI/maxresdefault.jpg', city_id: 3, user_id: 1, content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


p3 = Post.create title: 'Phuket is beautiful', image: 'https://images.trvl-media.com/hotels/1000000/70000/68800/68751/68751_232_z.jpg', city_id: 7, user_id: 1, content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'


p4 = Post.create title: 'Problem with traveling to Phuket', image: 'https://i.ytimg.com/vi/iXCW5t7asms/maxresdefault.jpg', city_id: 7, user_id: 3, content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

p5 = Post.create title: 'Sydney is wonderful', image: 'https://images.trvl-media.com/hotels/1000000/10000/2300/2220/e706ad98_z.jpg', city_id: 5, user_id: 2, content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas tortor non tincidunt tincidunt. Pellentesque vel luctus lacus. Phasellus euismod elementum dictum. Nam eget viverra nisi, sed sodales odio. Nunc malesuada ornare pharetra. Cras ac risus vel nisi pretium commodo sit amet et quam. Fusce at ornare ante, id vulputate urna. Etiam auctor turpis sed blandit viverra. Morbi lobortis dolor magna, vestibulum feugiat sem rutrum eu.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus bibendum in nulla nec sollicitudin. Mauris eleifend accumsan neque nec pellentesque. Duis laoreet bibendum ante. Praesent a congue diam. Praesent quis est ut augue blandit pretium fermentum in est. Donec non viverra ante, sed cursus tortor. Integer iaculis tincidunt metus at dictum. Nunc aliquam eu quam sit amet elementum. Ut a neque interdum, fermentum magna eu, gravida diam. Mauris eu euismod sem. Fusce fermentum, lorem quis scelerisque imperdiet, dolor ante convallis massa, sit amet blandit magna dolor sed metus. Donec quis aliquet velit. Duis efficitur diam et lorem bibendum bibendum. Sed in porttitor justo.

Phasellus a velit pellentesque, tristique eros ut, facilisis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pulvinar metus ac nunc viverra tincidunt. Nulla condimentum eleifend ipsum sed lobortis. Sed ullamcorper, orci euismod imperdiet viverra, dui tellus tristique nisi, id rhoncus lorem nulla sed sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet viverra elit. Quisque eu ipsum vitae nisl lacinia ultricies. Nam accumsan dui a feugiat efficitur. Aenean pharetra augue mi, vitae dictum tellus egestas ac. Phasellus rhoncus sagittis lectus id sodales. Cras ut lorem felis. Integer sed suscipit diam. Sed orci nisi, semper vitae turpis ac, aliquet suscipit ante. Mauris sed dictum felis. Etiam tincidunt mollis mi eget elementum.'

puts "Created #{Post.all.length} posts."


Photo.destroy_all

o1 = Photo.create image: 'https://media.timeout.com/images/103881996/630/472/image.jpg', city_id: 5
o2 = Photo.create image: 'https://mydetour.com.au/wp-content/uploads/2015/09/My-Detour-Private-Sydney-Tour-1.png', city_id: 5
o3 = Photo.create image: 'https://weeklytimes.com.au/wp-content/uploads/2018/01/TarongeCentenaryHeader-678x381.jpg', city_id: 5
o4 = Photo.create image: 'https://www.movenpick.com/fileadmin/_processed_/e/8/csm_save_and_stay_beach_18_5a12a640be.jpg', city_id: 7
o5 = Photo.create image: 'https://www.thetravelword.com/wp-content/uploads/2014/05/thailand-phuket-market-bangla.jpg', city_id: 7
o6 = Photo.create image: 'https://media.nomadicmatt.com/lisboncity1.jpg', city_id: 8
o7 = Photo.create image: 'https://d2kmm3vx031a1h.cloudfront.net/RmTDena4Seq3l5ukZMe6_16936189_10210992136333259_215753632_o.jpg', city_id: 3
o8 = Photo.create image: 'https://media-cdn.tripadvisor.com/media/photo-s/12/98/44/33/los-angeles-and-hollywood.jpg', city_id: 9


puts "Created #{Photo.all.length} photos."
